// 20220312225722
// https://api.github.com/users/euconectei
export const userMock = {
  login: 'euconectei',
  id: 1842710,
  node_id: 'MDQ6VXNlcjE4NDI3MTA=',
  avatar_url: 'https://avatars.githubusercontent.com/u/1842710?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/euconectei',
  html_url: 'https://github.com/euconectei',
  followers_url: 'https://api.github.com/users/euconectei/followers',
  following_url:
    'https://api.github.com/users/euconectei/following{/other_user}',
  gists_url: 'https://api.github.com/users/euconectei/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/euconectei/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/euconectei/subscriptions',
  organizations_url: 'https://api.github.com/users/euconectei/orgs',
  repos_url: 'https://api.github.com/users/euconectei/repos',
  events_url: 'https://api.github.com/users/euconectei/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/euconectei/received_events',
  type: 'User',
  site_admin: false,
  name: 'Rafael França',
  company: null,
  blog: '',
  location: 'Rio de Janeiro, RJ - Brasil',
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 40,
  public_gists: 4,
  followers: 35,
  following: 7,
  created_at: '2012-06-12T14:02:34Z',
  updated_at: '2022-03-03T12:45:39Z',
};
